### ISSUE TITLE
Doesn't work with EasyCommandAutofill

### ISSUE THREAD

**Issue by KygekDev** [HimbeersaftLP/HideCommands#19]
The HideCommands plugin doesn't work (not hiding commands) if EasyCommandAutofill plugin is installed within the same server.

### How to Reproduce:
- Prepare a fresh PocketMine-MP server without any plugins.
- Install HideCommands and EasyCommandAutofill to the server.
- Start the server, edit HideCommands as you want, then restart the server.
- Join the server and you'll see all commands are still visible when typing `/` in the chat.

**Comment by HimbeersaftLP** [comment]
This is because EasyCommandAutofill uses the event priority HIGHEST:
https://github.com/pmmp/PocketMine-MP/blob/8fb4d7b982dbb5c7f7792d203889ec678c5cec61/src/pocketmine/event/EventPriority.php#L70

I could work around the issue by setting it to MONITOR, but editing the event there is not recommended:
https://github.com/pmmp/PocketMine-MP/blob/8fb4d7b982dbb5c7f7792d203889ec678c5cec61/src/pocketmine/event/EventPriority.php#L71-L76

I am not sure if Poggit would approve a plugin that edits the event in a MONITOR listener.

Maybe there is also a way to do it with plugin.yml dependencies to change the load order, but that also sounds kinda hacky.

**Comment by KygekDev** [comment]
`MONITOR` is only used for monitoring the outcome of an event.

https://devdoc.pmmp.io/events-spec.html#list-of-priorities

> `MONITOR`: These handlers will execute last. **No modification to the event’s outcome should be made at this priority, including cancellation.** This should be used to only for monitoring the outcome of an event.

**Comment by HimbeersaftLP** [comment]
That's literally what I said...

**Comment by HimbeersaftLP** [comment]
So?

**Comment by KygekDev** [comment]
> So?

I think we need to think of using other workarounds, besides setting the event priority to `MONITOR`

**Comment by HimbeersaftLP** [comment]
The priority of EasyCommandAutofill was lowered in this commit: https://github.com/jasonwynn10/EasyCommandAutofill/commit/13d433b3c609927a159f6fac55d9445b828e5b4c
So we can just use HIGHEST now.

**Comment by KygekDev** [comment]
Thanks
